SELECT CODPRODPA
FROM (
    SELECT 
        MP.CODPRODPA,
        ROW_NUMBER() OVER(PARTITION BY MP.CODPRODPA ORDER BY PRC.VERSAO DESC) AS RN
    FROM TPRLMP MP
    INNER JOIN TPRATV ATV ON ATV.IDEFX = MP.IDEFX
    INNER JOIN TPRPRC PRC ON PRC.IDPROC = ATV.IDPROC
    WHERE MP.CODPRODMP = {CODPRODMP}
      AND PRC.CODPRC = 40
)
WHERE RN = 1 
  AND ROWNUM = 1 -- Garante o retorno de apenas uma única linha no resultado final