SELECT 
    PRC.CODPRC, 
    PRC.DESCRABREV AS DESCRICAO_PROCESSO, 
    PRC.VERSAO, 
    MP.CODPRODPA AS COD_PA, 
    PA.DESCRPROD AS DESCRICAO_PA, 
    MP.CODPRODMP AS COD_MP, 
    MP_PROD.DESCRPROD AS DESCRICAO_MP, 
    MP.CODVOL AS UNIDADE, 
    MP.QTDMISTURA AS QTD_PADRAO,
    'Principal' AS TIPO_COMPONENTE
FROM TPRLMP MP
INNER JOIN TPRATV ATV ON ATV.IDEFX = MP.IDEFX
INNER JOIN TPRPRC PRC ON PRC.IDPROC = ATV.IDPROC
INNER JOIN TGFPRO PA ON PA.CODPROD = MP.CODPRODPA
INNER JOIN TGFPRO MP_PROD ON MP_PROD.CODPROD = MP.CODPRODMP
WHERE MP.CODPRODPA = :P_CODPRODPA -- Informe o código do Produto Acabado aqui

UNION ALL

SELECT 
    PRC.CODPRC, 
    PRC.DESCRABREV AS DESCRICAO_PROCESSO, 
    PRC.VERSAO, 
    MPA.CODPRODPA AS COD_PA, 
    PA.DESCRPROD AS DESCRICAO_PA, 
    MPA.CODPRODMPALT AS COD_MP, 
    MPA_PROD.DESCRPROD AS DESCRICAO_MP, 
    MPA.CODVOL AS UNIDADE, 
    MPA.QTDMISTURA AS QTD_PADRAO,
    'Alternativo' AS TIPO_COMPONENTE
FROM TPRMPA MPA
INNER JOIN TPRATV ATV ON ATV.IDEFX = MPA.IDEFX
INNER JOIN TPRPRC PRC ON PRC.IDPROC = ATV.IDPROC
INNER JOIN TGFPRO PA ON PA.CODPROD = MPA.CODPRODPA
INNER JOIN TGFPRO MPA_PROD ON MPA_PROD.CODPROD = MPA.CODPRODMPALT
WHERE MPA.CODPRODPA = :P_CODPRODPA

ORDER BY 
    VERSAO DESC, 
    TIPO_COMPONENTE DESC, 
    DESCRICAO_MP;